config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :articles
  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_articles, only: [:show, :edit, :update, :destroy, :edit]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to article_path(@article)
  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article.destroy
    redirect_to articles_path, notice: "Artículo elimindado"
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end

  def set_articles
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<%= form_with model: @article, local: true do |form| %>
<%= form.label :title, "Título" %> <%= form.text_field :title, placeholder: "", class: "title-input" %>
<%= form.label :content, "Contenido" %> <%= form.text_area :content, rows: 10, class: "content-textarea" %>
<%= form.submit "Crear Artículo", class: "submit-btn" %> <%= link_to "Volver", articles_path, class: "back-link" %>
<% end %>

app/views/articles/index.html.erb
<div class="container">
  <ul>
    <% @articles.each do |article| %>
      <li><%= link_to "#{article.title}", article_path(article) %></li>
      <p><%= "#{article.content}" %></p>
    <% end %>
  </ul>
</div>

app/views/articles/new.html.erb
<%= form_with model: @article, local: true do |form| %>
<%= form.label :title, "Título" %> <%= form.text_field :title, placeholder: "", class: "title-input" %>
<%= form.label :content, "Contenido" %> <%= form.text_area :content, rows: 10, class: "content-textarea" %>
<%= form.submit "Crear Artículo", class: "submit-btn" %> <%= link_to "Volver", articles_path, class: "back-link" %>
<% end %>

app/views/articles/show.html.erb
<div class="container-show">
  <h1>
  <%= "#{@article.title}" %>
  <%= link_to edit_article_path(@article) do %>
    <i class="fa fa-pencil"></i>
  <% end %>
  <%= link_to article_path(@article), data: { turbo_method: :delete, turbo_confirm: "Seguro?" } do %>
    <i class="fa fa-trash"></i>
  <% end %>
  </h1>
  <h2><%= "#{@article.content}" %></h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
  <nav class="navbar bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" ><%= link_to "Wikinimous", articles_path %></a>
        <button class="btn btn-primary" type="submit">New Article</button>
      </form>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>